FROM node:20.12.0-alpine3.19

WORKDIR /usr/src/app

COPY ./server/package.json ./server/package-lock.json  ./server/tsconfig.json ./

RUN npm install

COPY server .

RUN npm run db:generate

RUN npm run build

CMD ["npm", "run", "dev"]